# Description:
#   Generates random expressions for doing the number two
#
# Commands:
#   boston - generates random expressions for doing the number two

evacuations = [
  "Evacuar",
  "Atender o chamado da natureza",
  "Construir uma barragem",
  "Ir para o trono",
  "Fazer uma sopa de feijão",
  "Expelir a solitária",
  "Assinar o divórcio",
  "Cortar nhoque",
  "Pendurar a sucuri",
  "Depositar no banco de Boston",
  "Fabricar Chocolate",
  "Mandar o Obama para Casa Branca",
  "Prepara Milk Shake de chocolate",
  "Bater um barro",
  "Aliviar",
  "Fazer Tôtô",
  "Brincar de massinha",
  "Livrai-me do mal, amém",
  "Tirar a tartaruga do saco",
  "Ir ao toalete",
  "Emborcar",
  "Esvaziar",
  "Manchar a porcelana",
  "Morder bombom",
  "Mandar o Elevador para o térreo",
  "Apontar o lápis",
  "Dar uma barrigada",
  "Invadir propriedade privada",
  "Mandar um torpedo",
  "Peidar molhado",
  "Contar Milho",
  "Cuspir o charuto",
  "Apontar a luneta pro bueiro",
  "Ir na casinha",
  "Molhar o beiço de baixo",
  "Defecar",
  "Picar pepino",
  "Obrar",
  "Levar um amigo do interior para o rio",
  "Fazer força",
  "Lançar o submarino marrom",
  "Desentupir o intestino",
  "Marcar território",
  "Filosofar sentado",
  "Tirar o plástico da mortadela",
  "Correr um bronze",
  "Sessão de descarrego",
  "Parir pelo buraco errado",
  "Mandar um BBB para o paredão",
  "Despejar o inquilino",
  "Cagar",
  "Se borrar",
  "Semear a discórdia",
  "Cortar o rabo do macaco",
  "Fazer um download",
  "Chapiscar a percelana",
  "Bater um papo com o bocão",
  "Se despedir do pessoal",
  "Visitar a dona Celite",
  "Excretar",
  "Desocupar o organismo",
  "Se despedir do almoço",
  "Descomer",
  "Vomitar pelo cu",
  "Fazer sujeira",
  "Piscar pro bocão",
  "Arrancar a cabeça do playmobil",
  "Entupir o esgoto",
  "Perder uns quilos",
  "Grafitar a louça",
  "Castigar a cerâmica",
  "Emporcalhar",
  "Enfezar",
  "Destampar a panela de barro",
  "Relaxar o esfíncter",
  "Botar os peixes no aquário",
  "Botar um ovo escuro",
  "Coar café",
  "Fazer cocô",
  "Levar as crianças para a natação",
  "Esmerdear ",
  "Molhar o cabo do guarda-chuva ",
  "Fazer o número dois",
  "Calcular o produto interno bruto",
  "Escorregar o moreno",
  "Fazer carvão",
  "Compor com o Ary Barroso",
  "Dar um cagote",
  "Soltar um exremento",
  "Escoar a produção",
  "Estercar",
  "Fazer das tripas coração",
  "Afogar o moreninho",
  "Fazer uma revisão no escapamento",
  "Passar um fax",
  "Fazer um boneco",
  "Pendurar a badalhoca",
  "Resolver um problema de cunho pessoal",
  "Fritar Churros"
]

module.exports = (robot) ->

 robot.hear /fax|evacuar|boston/i, (msg) ->
   msg.send "Você quis dizer: #{msg.random evacuations}?"